### PR TITLE
adding grunt log

### PR DESCRIPTION
**Pull request by tymondesigns**

### CODE REVIEW

**Comment by yfr** [comment]
Nice adition. But travis failed because of `grunt: not found`. Maybe we should set up some tests.

**Comment by tymondesigns** [comment]
Yea, i'd be willing to help out with tests when I can.
I have also opened #3

**Comment by tymondesigns** [comment]
In the mean time would you be willing to bump the version with these PR's ?

**Comment by yfr** [comment]
Did the looking-at-it test cases. Seems to be fine. But yeah maybe we should just open an issue for that.

**Comment by yfr** [comment]
Funny #1 is allready for test cases ... so next task!

**Comment by tymondesigns** [comment]
Thanks for that :smile:

**Pull request merged**
